Export all variables that starts with REACT (#15)

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,6 +23,9 @@ if [ -f "$BUILD_DIR/node_modules/.bin/turbo" ]; then
   echo "-----> ⌛️  Building frontend"
 
   export SKIP_SOURCEMAPS_UPLOAD=$ENV_SKIP_SOURCEMAPS_UPLOAD
+  for file in $(ls "$ENV_DIR" | grep "^REACT"); do
+    export $(echo "$file")=$(cat "$ENV_DIR/$file" 2>/dev/null || true)
+  done
 
   cd "$BUILD_DIR"
   yarn build:apps:heroku
@@ -34,7 +37,7 @@ fi
 if [ -n "$ENV_ROLE_ARN" ] && [ -n "$ENV_S3_BUCKET_NAME" ] && [ -n "$ENV_DISTRIBUTION_ID" ] && \
    [ -n "$ENV_AWS_ACCESS_KEY_ID" ] && [ -n "$ENV_AWS_SECRET_ACCESS_KEY" ] && \
    [ -n "$ENV_HEROKU_APP_NAME" ] && [ -n "$ENV_HEROKU_RELEASE_VERSION" ]; then
-  echo "-----> ⌛️  Starting Cloudfront upload and invalidation process" 
+  echo "-----> ⌛️  Starting Cloudfront upload and invalidation process"
   echo "-----> ⌛️  Setting env variables"
   # Set env variables for aws cli
   export AWS_ACCESS_KEY_ID="$ENV_AWS_ACCESS_KEY_ID"
@@ -50,7 +53,7 @@ if [ -n "$ENV_ROLE_ARN" ] && [ -n "$ENV_S3_BUCKET_NAME" ] && [ -n "$ENV_DISTRIBU
   echo "-----> ✅  Role assumed successfully"
 
   echo "-----> ⌛️  Setting new temporary env variables from assumed role"
-  
+
   # Unset env variables for aws cli
   unset AWS_SECRET_ACCESS_KEY
   unset AWS_ACCESS_KEY_ID
@@ -99,5 +102,3 @@ rm -rf "$BUILD_DIR/node_modules" \
   "$BUILD_DIR/.heroku/node"
 
 echo "-----> ✅  Cleaning up slug successfully"
-
-
